name: Testing ContextVariables

on:
  workflow_dispatch:

env:
  cloud: google

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking Context Variables" 
        run: |
          echo "Event_name: ${{ github.event_name }}"
          echo "Repo_name: ${{ github.repository }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Ref: ${{ github.ref }}"
          echo "Triggering_actor: ${{ github.triggering_actor }}"
          echo "User_name: ${{ github.event.user.name }}"
          echo "Github Action: ${{ github.action }}"
          echo "User: ${{ github.actor }}"
